### ISSUE TITLE
Move to using just "python3"

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/AnalysisTools#19]
As we move to Ubuntu 16.04, this comes with Python 3.5 installed, and so all of the static analysis tools are broken as they all have a hard dependency on 3.4.

I'd like to replace all `#!/usr/bin/env python3.4` shebang lines with `#!/usr/bin/env python3` unless there's something that would only work with that version of python and nothing higher (which there shouldn't be?)

**Comment by bmcutler** [comment]
done in PR #22
